---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-data
spec:
  volumeName: mongo-pv
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

